# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='producer_id_hash',
        ),
    ]
