# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_remove_beer_producer_id_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='producer_id_hash',
            field=models.CharField(default=uuid.uuid1, max_length=32),
        ),
    ]
